# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    machine: true
    steps:
    - add_ssh_keys:
        fingerprint: 
        - "c9:2a:56:ee:a0:fa:63:c7:5d:f5:1f:24:9e:e5:52:59"
    - checkout
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: docker build -t jese69/OSII_API:$CIRCLE_SHA1 .
    - run: docker push jese69/OSII_API:$CIRCLE_SHA1
    - run: ssh -o StrictHostKeyChecking=no JeseAzure@23.101.180.53 "/bin/bash /root/docker/deploy.sh $CIRCLE_SHA1"

